"""Build tools — compile_latex, scaffold_project.

Compile uses the 3-layer template stack:
  - App layer: classes + skeletons under <repo>/plugin/templates/
  - Office layer: office-style.sty + auto-generated office-identity.tex
                  under <state_root>/templates/ (paths.office_style_dir)
  - Project layer: per-project Projektdaten.tex + master .tex

TEXINPUTS is composed from these three layers so latexmk finds the
right files regardless of where they live on disk.
"""
from __future__ import annotations

import logging
import os
import re
import shutil
import subprocess
from pathlib import Path

from pbs_mcp import config, office_config
from pbs_mcp.schemas import (
    CompileLatexInput,
    CompileLatexOutput,
    ScaffoldProjectInput,
    ScaffoldProjectOutput,
)

logger = logging.getLogger(__name__)


def _escape_tex(s: str) -> str:
    """Escape user-supplied identity strings for safe LaTeX inclusion."""
    return (
        s.replace("\\", "\\textbackslash{}")
        .replace("{", "\\{")
        .replace("}", "\\}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("$", "\\$")
        .replace("#", "\\#")
        .replace("_", "\\_")
        .replace("~", "\\textasciitilde{}")
        .replace("^", "\\textasciicircum{}")
    )


def _generate_identity_macros(cfg) -> str:
    """Render office-identity.tex from identity section of office-config."""
    ident = cfg.identity
    addr_lines = "".join(f"  {_escape_tex(line)}\\\\\n" for line in ident.address_lines)
    lines = [
        "% office-identity.tex — auto-generated by pbs-mcp from office-config.",
        "% Do not edit by hand; changes will be overwritten on next compile.",
        "",
        f"\\providecommand{{\\OfficeName}}{{{_escape_tex(cfg.office.name)}}}",
        f"\\providecommand{{\\OfficeShort}}{{{_escape_tex(cfg.office.short)}}}",
        "\\providecommand{\\OfficeAddressLines}{%",
        addr_lines.rstrip(),
        "}",
    ]
    if ident.title:
        lines.append(f"\\providecommand{{\\OfficeTitle}}{{{_escape_tex(ident.title)}}}")
    if ident.phone:
        lines.append(f"\\providecommand{{\\OfficePhone}}{{{_escape_tex(ident.phone)}}}")
    if ident.mobile:
        lines.append(f"\\providecommand{{\\OfficeMobile}}{{{_escape_tex(ident.mobile)}}}")
    if ident.fax:
        lines.append(f"\\providecommand{{\\OfficeFax}}{{{_escape_tex(ident.fax)}}}")
    if ident.email:
        lines.append(f"\\providecommand{{\\OfficeEmail}}{{{_escape_tex(ident.email)}}}")
    if ident.web:
        lines.append(f"\\providecommand{{\\OfficeWeb}}{{{_escape_tex(ident.web)}}}")
    if ident.specializations:
        spec_lines = "".join(f"  {_escape_tex(s)}\\\\\n" for s in ident.specializations)
        lines.append("\\providecommand{\\OfficeSpecializations}{%")
        lines.append(spec_lines.rstrip())
        lines.append("}")
    if ident.logo_path:
        # LaTeX needs forward slashes; \graphicspath uses braces around dirs
        lines.append(f"\\providecommand{{\\OfficeLogoPath}}{{{str(ident.logo_path).replace(chr(92), '/')}}}")
    if ident.signature_image_path:
        lines.append(f"\\providecommand{{\\OfficeSignaturePath}}{{{str(ident.signature_image_path).replace(chr(92), '/')}}}")
    # Escape per-line first, THEN join with LaTeX line breaks, so the
    # LaTeX line-break syntax doesn't get double-escaped.
    escaped_sig_lines = [_escape_tex(line) for line in ident.signature_block.splitlines() if line.strip()]
    sig = "\\\\\n".join(escaped_sig_lines)
    lines.append(f"\\providecommand{{\\OfficeSignatureBlock}}{{%\n{sig}}}")
    default = cfg.default_practice()
    signer = default.signer or ""
    if signer:
        lines.append(f"\\providecommand{{\\OfficeSigner}}{{{_escape_tex(signer)}}}")
    return "\n".join(lines) + "\n"


def _refresh_identity_macros() -> Path | None:
    """Regenerate office-identity.tex if templates.identity_macros == 'auto'.

    Returns the path on success, None if hand-maintained or write failed.
    """
    cfg = office_config.load()
    tpl = cfg.templates
    if tpl.identity_macros != "auto":
        return None  # hand-maintained; don't touch
    style_dir = tpl.office_style_dir
    if style_dir is None:
        return None
    style_dir.mkdir(parents=True, exist_ok=True)
    out = style_dir / "office-identity.tex"
    out.write_text(_generate_identity_macros(cfg), encoding="utf-8")
    return out


def _texinputs(project_dir: Path) -> str:
    """Compose TEXINPUTS in the right order: project, office, app, system."""
    cfg = office_config.load()
    parts: list[str] = [str(project_dir)]
    if cfg.templates.office_style_dir:
        parts.append(str(cfg.templates.office_style_dir))
    parts.append(str(config.app_classes_dir()))
    parts.append(str(config.app_skeletons_dir()))
    if cfg.templates.skeleton_source != "app":
        parts.append(cfg.templates.skeleton_source)
    parts.append("")  # trailing empty = include default kpathsea path
    return os.pathsep.join(parts)


def compile_latex(input: CompileLatexInput) -> CompileLatexOutput:
    project_dir = Path(input.project_path)
    if not project_dir.is_dir():
        raise FileNotFoundError(f"not a directory: {project_dir}")

    _refresh_identity_macros()

    master = input.master_file
    if not master:
        # Auto-detect: look for a file with `\documentclass` at top level
        candidates = list(project_dir.glob("*.tex"))
        for c in candidates:
            try:
                head = c.read_text(encoding="utf-8")[:2000]
                if "\\documentclass" in head:
                    master = c.name
                    break
            except UnicodeDecodeError:
                pass
        if not master:
            return CompileLatexOutput(
                success=False,
                pdf_path=None,
                log_excerpt="No master .tex file with \\documentclass found",
                warnings=[],
                errors=["No master .tex file detected"],
                page_count=None,
            )

    master_path = project_dir / master
    if not master_path.is_file():
        return CompileLatexOutput(
            success=False, pdf_path=None,
            log_excerpt=f"master file not found: {master}",
            warnings=[], errors=[f"master file not found: {master}"],
            page_count=None,
        )

    pdf_name = master_path.stem + ".pdf"
    log_name = master_path.stem + ".log"

    # Prefer latexmk; fall back to pdflatex
    if shutil.which("latexmk"):
        cmd = ["latexmk", "-pdf", "-interaction=nonstopmode", "-halt-on-error", master]
    else:
        cmd = ["pdflatex", "-interaction=nonstopmode", "-halt-on-error", master]

    env = {**os.environ, "TEXINPUTS": _texinputs(project_dir)}

    try:
        result = subprocess.run(
            cmd,
            cwd=project_dir,
            capture_output=True,
            text=True,
            timeout=600,
            env=env,
        )
        success = result.returncode == 0
    except subprocess.TimeoutExpired:
        return CompileLatexOutput(
            success=False, pdf_path=None,
            log_excerpt="compile timed out after 600s",
            warnings=[], errors=["compile timeout"],
            page_count=None,
        )

    log_path = project_dir / log_name
    log_text = log_path.read_text(encoding="utf-8", errors="ignore") if log_path.is_file() else result.stdout

    warnings = re.findall(r"^.*[Ww]arning:.*$", log_text, flags=re.MULTILINE)
    errors = re.findall(r"^!.+$", log_text, flags=re.MULTILINE)

    pdf_path = project_dir / pdf_name
    page_count = None
    if pdf_path.is_file() and shutil.which("pdfinfo"):
        try:
            info = subprocess.run(
                ["pdfinfo", str(pdf_path)], capture_output=True, text=True, timeout=10
            )
            m = re.search(r"^Pages:\s+(\d+)", info.stdout, flags=re.MULTILINE)
            if m:
                page_count = int(m.group(1))
        except (subprocess.TimeoutExpired, OSError):
            pass

    return CompileLatexOutput(
        success=success and pdf_path.is_file(),
        pdf_path=str(pdf_path) if pdf_path.is_file() else None,
        log_excerpt="\n".join(log_text.splitlines()[-50:]),
        warnings=warnings[:20],
        errors=errors[:20],
        page_count=page_count,
    )


def scaffold_project(input: ScaffoldProjectInput) -> ScaffoldProjectOutput:
    """Copy template tree to a new project root; optionally git-init LaTeX dirs.

    Template resolution:
      1. Explicit `template_repo` input wins.
      2. Office-config `templates.doctype_overrides[<doctype>]` if set.
      3. App's shipped skeleton at <repo>/plugin/templates/skeletons/<doctype>.

    For new offices with no override, the app skeleton is the canonical
    starting point: a minimal master + Projektdaten template that pulls
    in office-style.sty + auto-generated office-identity.tex via TEXINPUTS.
    """
    target = Path(input.target_root)
    if target.exists():
        raise FileExistsError(f"target already exists: {target}")

    cfg = office_config.load()
    if input.template_repo:
        template = Path(input.template_repo)
    elif input.doctype in cfg.templates.doctype_overrides:
        template = cfg.templates.doctype_overrides[input.doctype]
    else:
        skeleton_dir = config.app_skeletons_dir() / input.doctype
        if skeleton_dir.is_dir():
            template = skeleton_dir
        else:
            raise FileNotFoundError(
                f"no skeleton shipped for doctype '{input.doctype}'. "
                f"Set templates.doctype_overrides.{input.doctype} in "
                f"office-config or pass template_repo explicitly."
            )

    if not template.is_dir():
        raise FileNotFoundError(f"template not found: {template}")

    # Copy tree, excluding build artifacts and git history
    EXCLUDE = {".git", ".aux", ".fdb_latexmk", ".fls", ".log", ".lot",
               ".pdf", ".synctex.gz", ".toc", ".png", ".jpg", "image"}

    def _ignore(d, names):
        return [n for n in names if any(n.endswith(e) or n.startswith(e) for e in EXCLUDE)]

    target.mkdir(parents=True, exist_ok=True)
    shutil.copytree(template, target, ignore=_ignore, dirs_exist_ok=True)

    created_paths = [str(target)]

    # Patch Projektdaten.tex with provided project data
    projektdaten = target / "Projektdaten.tex"
    if projektdaten.is_file() and input.project_data:
        text = projektdaten.read_text(encoding="utf-8")
        for key, value in input.project_data.items():
            # Replace \newcommand{\Key}{old} with \newcommand{\Key}{new}
            pat = rf"\\newcommand\{{\\{key}\}}\{{[^}}]*\}}"
            new = f"\\newcommand{{\\{key}}}{{{value}}}"
            text = re.sub(pat, new, text)
        projektdaten.write_text(text, encoding="utf-8")

    # git init for Overleaf sync
    git_repos: list[str] = []
    if input.git_init_latex and shutil.which("git"):
        try:
            subprocess.run(
                ["git", "init", "-b", "main"], cwd=target, check=True, capture_output=True, timeout=30
            )
            git_repos.append(str(target))
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
            logger.warning(f"git init failed for {target}")

    return ScaffoldProjectOutput(
        name=input.name,
        project_root=str(target),
        created_paths=created_paths,
        git_repos_initialized=git_repos,
    )
